@node1 = http://localhost:3001
@node2 = http://localhost:3002
@node3 = http://localhost:3003

@node4 = http://localhost:3004

@node5 = http://localhost:3005


###
GET {{node1}}/api/peers

###
GET {{node2}}/api/peers

###
GET {{node3}}/api/peers

###
GET {{node4}}/api/peers

###
GET {{node5}}/api/peers


###
GET {{node2}}/api/blockchain



###
POST {{node5}}/api/sendToPeers
Content-Type: application/json

{
    "message": "{{$guid}}"
}

###
POST {{node2}}/api/wallet
Content-Type: application/json

{
    "password": "password"
}

###
POST {{node2}}/api/wallet/keys
Content-Type: application/json

{
    "password": "password"
}


###
POST {{node1}}/api/mine
Content-Type: application/json

{
}

###
GET {{node1}}/api/balance
Content-Type: application/json

{
}


###
POST {{node1}}/api/mineTransaction
Content-Type: application/json

{
    "address": "04a0842c5b3553092381dff2b1baf106d708783b3a98a314674c18b35a3a918912df4a394a139d615e12d36067782faf3495daa9e5363eeeea32318b096fd20da0",
    "amount": 20
}