@node1 = http://localhost:3001
@node2 = http://localhost:3002
@node3 = http://localhost:3003

@node4 = http://localhost:3004

@node5 = http://localhost:3005


###
GET {{node1}}/api/peers

###
GET {{node2}}/api/peers

###
GET {{node3}}/api/peers

###
GET {{node4}}/api/peers

###
GET {{node5}}/api/peers


###
GET {{node1}}/api/blockchain



###
POST {{node5}}/api/sendToPeers
Content-Type: application/json

{
    "message": "{{$guid}}"
}

###
POST {{node1}}/api/wallet
Content-Type: application/json

{
    "password": "password"
}

###
POST {{node1}}/api/wallet/keys
Content-Type: application/json

{
    "password": "password"
}


###
POST {{node2}}/api/mine
Content-Type: application/json

{
    "data": "test"
}
