@node1 = http://localhost:3001
@node2 = http://localhost:3002
@node3 = http://localhost:3003

@node4 = http://localhost:3004

@node5 = http://localhost:3005


###
GET {{node1}}/api/peers

###
GET {{node2}}/api/peers

###
GET {{node3}}/api/peers

###
GET {{node4}}/api/peers

###
GET {{node5}}/api/peers


###
GET {{node2}}/api/blockchain



###
POST {{node5}}/api/sendToPeers
Content-Type: application/json

{
    "message": "{{$guid}}"
}

###
POST {{node1}}/api/wallet
Content-Type: application/json

{
    "password": "password"
}

###
POST {{node1}}/api/wallet/keys
Content-Type: application/json

{
    "password": "password"
}


###
POST {{node3}}/api/mine
Content-Type: application/json

{
}

###
GET {{node2}}/api/balance
Content-Type: application/json

{
}


###
POST {{node3}}/api/mineTransaction
Content-Type: application/json

{
    "address": "04162c630a0db9a6438ae01f5a5d11e3a89245c6b5cf94ca5e7c552a6c170c9d7f5867897a0eb8974dc539b646d12a08c98349d0658074df10d19fa35c77070f80",
    "amount": 50
}

###
POST {{node3}}/api/sendTransaction
Content-Type: application/json

{
    "address": "04d932aeefcd77a0b21bb3be816bd6847250ab4b02013416c65b30b2addc141da133dc58294e6e463e13539d3cf1514ee2ad237c08a8912706dfe6fc1143ce447b",
    "amount": 50
}

###
GET {{node1}}/api/transactionPool
Content-Type: application/json